# Generated by Django 5.1.1 on 2024-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=5)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
