# Generated by Django 5.1.1 on 2024-11-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_file_media_photo_media_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
    ]
